name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

<<<<<<< HEAD
    - name: build
      run: make -B -j$(nproc)
=======
    - name: Install dependencies
      run: make dependencies

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
>>>>>>> 3d46b30283fabf9080e973cdd7688267d83749f6
